# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlisho', '0004_auto_20160317_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastoralist',
            name='community',
            field=models.CharField(blank=True, choices=[(b'Lemek', b'Lemek'), (b'Ol Chorro', b'Ol Chorro'), (b'Talek', b'Talek'), (b'Keekerok', b'Keekerok')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='country',
            field=models.CharField(blank=True, choices=[(b'Kenya', b'Kenya'), (b'Tanzania', b'Tanzania'), (b'Mali', b'Mali'), (b'Botswana', b'Botswana')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='district',
            field=models.CharField(blank=True, choices=[(b'Githii', b'Githii'), (b'Muhito', b'Muhito'), (b'Gakindu', b'Gakindu'), (b'Gikondi', b'Gikondi')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='familysize',
            field=models.CharField(blank=True, choices=[(b'5', b'5'), (b'10', b'10'), (b'15', b'15'), (b'25', b'25')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='location',
            field=models.CharField(blank=True, choices=[(b'Lemek', b'Lemek'), (b'Ol Chorro', b'Ol Chorro'), (b'Talek', b'Talek'), (b'Keekerok', b'Keekerok')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='province',
            field=models.CharField(blank=True, choices=[(b'Rift Valley', b'Rift Valley'), (b'North Easter', b'North Easter'), (b'Eastern', b'Eastern'), (b'Coast', b'Coast')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pastoralist',
            name='village',
            field=models.CharField(blank=True, choices=[(b'Lemek', b'Lemek'), (b'Ol Chorro', b'Ol Chorro'), (b'Talek', b'Talek'), (b'Keekerok', b'Keekerok')], max_length=15, null=True),
        ),
    ]
