# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 22:51
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mlisho', '0005_auto_20160317_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastoralist',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=datetime.datetime(2016, 3, 16, 22, 51, 19, 789079, tzinfo=utc), srid=4326),
            preserve_default=False,
        ),
    ]
